// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mysqldb

import (
	"time"
)

type Product struct {
	ID          string
	Name        string
	Description string
	Price       int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
